### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by roblandry** [roblandry/kluster-template#48]
Items that need to be fixed at some point:
- [ ] Homepage (calibre-web widget) - password special characters not escaped
- [ ] Homepage (photoprism widget) - password special characters not escaped
- [ ] Homepage (pfsense widget) - password special characters not escaped
